### PR TITLE
feat: add simple test

### PR DESCRIPTION
**Pull request by zhoukekestar**
add unit test for esm.sh. #44

### CODE REVIEW

**Comment by zhoukekestar** [comment]
We just need check variable exist or not in most case. If esm.sh import works and has no-undefined variable, it's always works for me.

**Comment by zhoukekestar** [comment]
By the way, it's very very hard to pass all unit test.  😂
> We use so many hack way to pass it.   =_= |

**Review by ije — COMMENTED** [review]
looks great! thanks!

**Comment by ije** [comment]
@zhoukekestar i will make it pass all the tests, thanks

**Comment by zhoukekestar** [comment]
Some hack details maybe useful for you:
* named export solution PRed by @wleonardo 
* some npm packaged by webpack
* some npm use browser entry directly. For example: https://unpkg.com/browse/yargs@16.2.0/browser.mjs
* some necessary polyfill like: @jspm/core & entends it. For example: https://github.com/jspm/jspm-core/issues/13

**Pull request merged**
